apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-something
  namespace: zoyirjon-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  template:
    metadata:
      labels:
        app: frontend-something
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      containers:
      - name: frontend-something
        image: nvrbckdown/something
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-something
spec:
  selector:
    app: frontend-something
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
