apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2025-04-11T16:26:28Z"
  name: reader
  resourceVersion: "20488685"
  uid: 0e6b56e5-d37d-4a15-91e1-9ee7009facde
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
