apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-admin-to-flask
  namespace: zoyirjon-final
spec:
  podSelector:
    matchLabels:
      app: flask-application
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: admin
    ports:
    - protocol: TCP
      port: 5000
