apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-04-11T14:32:11Z"
  generation: 1
  labels:
    app: flask-application
  name: flask-application
  namespace: zoyirjon-final
  resourceVersion: "20453879"
  uid: 3a2026a6-7b22-4498-b0e6-3f5f09c4be29
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-application
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-application
    spec:
      containers:
      - image: nvrbckdown/flask-app:last-practice
        imagePullPolicy: IfNotPresent
        name: flask-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
          requests:
            memory: "64Mi"
            cpu: "75m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
