apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-04-11T15:01:14Z"
  generation: 1
  labels:
    app: final-exam
  name: final-exam
  namespace: zoyirjon-final
  resourceVersion: "20462030"
  uid: 2cdb1547-2530-43ee-8c7e-a18fdf63bac1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: final-exam
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: final-exam
    spec:
      containers:
      - image: nvrbckdown/flask-app:final-exam
        imagePullPolicy: IfNotPresent
        name: flask-app
        env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: AUTHOR
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
